### ISSUE TITLE
bower_components以下のファイルのフォルダ名が長すぎる

### ISSUE THREAD

**Issue by kyasbal** [gamerinshaft/unitus-backbone#11]
bower_componentsの中のフォルダのネスト階層が深すぎてそちらのレポジトリをsubtreeとして管理できない。

![](http://i.gyazo.com/1bf30e6800d766ddd3dca582c82f4d83.png)

深い階層がgit的に管理される必要がないのであれば適切なgitignoreを設定してほしい。

**Comment by gamerinshaft** [comment]
了解

**Comment by gamerinshaft** [comment]
bower_componentsから中身を取り出して使っているみたいなのでignoreしました
