### ISSUE TITLE
実績リスト画面のカテゴリへの対応

### ISSUE THREAD

**Issue by kyasbal** [gamerinshaft/unitus-backbone#2]
# 作業内容

![08a7509137edf7ccfde986e9dc1e97ec](https://cloud.githubusercontent.com/assets/6434708/6387255/7cb249c2-bdcb-11e4-99c5-cf6439d11735.png)

赤色円部分にカテゴリの表示を付け加えるのと、黄色円部分に選択中のカテゴリを表示する。
# 実装について
## カテゴリのリスト取得処理

カテゴリのリストは、GET /Dashboardアクセス時に同時に返却するように変更済みである。(赤い円の部分)
![503361b3aab06d8c43e3662a36eaa6f6](https://cloud.githubusercontent.com/assets/6434708/6387283/2b137ba8-bdcc-11e4-986d-580bb8381dc9.png)
## カテゴリに属するリストの取得処理

現在ajaxへのAchivementsへのリクエストについてcategoryNameという引数を増やし、そこにカテゴリ名を指定してリクエストを送る。
例:なお、Ajaxで処理する際は当然だがアドレスに引数を入れる必要はないはず。

```
https://core.unitus-ac.com/Achivements?validationToken=as&categoryName=github
```

**Comment by gamerinshaft** [comment]
対応しました。
